#This app is intended to test and provide data to determine how much RAM is 
#really needed in a Ceph node.
#This requires cosbench & fio load generation workers
#prior to the test run, a check will be made of the ceph cluster to see if it is 
#at 75% of capacity.  If not, the cluster will be populated using the COSbench 
#workers to 85% with a mix of object sizes
#
#The formula for RAM will be to take total system memory and reduce it by 
#(numdevs * 4GB)
#This will be achieved by modifying the boot time parameters on the OSD nodes 
#using salt 
#cmd.run "sed -i -- 's/GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX=\"mem=xG\"/'" (check syntax)
#followed by grub2-mkconfig -o /boot/grub2/grub.cfg
#
#load would then be generated by running random fio workloads and COSbench 
#workloads simoultaneously
#statistics on cluster performance need to be captured in relation to RAM usage.  
#It would also be helpful to capture RAM usage per osd process
#at a timed interval, one of the OSD nodes will be powered off by IPMI resulting 
#in a node failure.
#workloads will continue to run during this time with the same statistics on 
#performance and RAM usage being captured.
#After the cluster health is OK, the powered off node is powered back on and 
#allowed to join the cluster, again, while load is being applied and statistics 
#are captured.
#After the test run is completed, RAM is decremented and the cluster is rebooted
# and the process continues down to a minimum RAM of OSD devices * 2GB
# NOTE: No other services or processes should be running on nodes during this test



